# Generated by Django 4.2.3 on 2023-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signed_pdf_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilesAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adminupload", models.FileField(upload_to="media")),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(name="SignedPDF",),
    ]
